defaults:
  - sft_coc_base_local
  - /models/qwen3vl2b_base@model
  - _self_

trainer:
  lr_multiplier:
    vlm.model.visual: 0.1
  ddp_find_unused_parameters: false
  gradient_accumulation_steps: 4
  learning_rate: 1e-5
  warmup_steps: 500
paths:
  output_dir: outputs/output_coc_stage1_2b
evaluate:
  eval_ckpt: null
