_target_: alpamayo_r1.processor.qwen_processor.get_preprocess_data_fn_from_model_config
components_order: ["image", "traj_history", "prompt", "cot", "traj_future"]
components_prompt: ["cot", "traj_future"]
label_components: ["cot", "traj_future"]
