_recursive_: false
_target_: finetune.sft.models.sft_base_model.TrainableReasoningVLA.from_qwen3vl_checkpoint
vlm_name_or_path: ckpts/Cosmos-Reason2-2B
traj_vocab_size: 4000
tokens_per_future_traj: 128
tokens_per_history_traj: 48
model_dtype: bfloat16
attn_implementation: flash_attention_2
add_special_tokens: true
min_pixels: 163840
max_pixels: 196608
traj_tokenizer_cfg:
  _recursive_: false
  _target_: alpamayo_r1.action_space.discrete_action_space.DiscreteTrajectoryTokenizer
  action_space_cfg:
    _target_: alpamayo_r1.action_space.UnicycleAccelCurvatureActionSpace
    a_lambda: 0.0001
    a_ridge: 0.0001
    accel_bounds: [-9.8, 9.8]
    accel_mean: 0.02902694707164455
    accel_std: 0.6810426736454882
    curvature_bounds: [-0.33, 0.33]
    curvature_mean: 0.0002692167976330542
    curvature_std: 0.026148280660833106
    dt: 0.1
    kappa_lambda: 0.0001
    kappa_ridge: 0.0001
    n_waypoints: 64
    theta_lambda: 1.0e-06
    theta_ridge: 1.0e-08
    v_lambda: 1.0e-06
    v_ridge: 0.0001
  dims_min: [-10, -10]
  dims_max: [10, 10]
  num_bins: 3000
hist_traj_tokenizer_cfg:
  _target_: alpamayo_r1.models.delta_tokenizer.DeltaTrajectoryTokenizer
